package suricata

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// apply.go is the privileged half, and it is deliberately the smallest half.
//
// meerkat's own service account cannot write /etc/suricata, cannot run
// suricata-update, and cannot open a root-owned control socket — by design. It
// parses attacker-influenced input all day and holds no capabilities at all.
// So the work is split: the unprivileged console decides *what* the ruleset
// should be and writes the filter files into its own state directory, and this
// code — run as root by a systemd oneshot, or by hand — does the four
// mechanical steps that need privilege and writes back what happened.
//
// Nothing here makes a decision. It installs files it is given, runs one
// program, asks Suricata to reload, and reports. That is the entire privileged
// surface.

// generatedMarker identifies a filter file meerkat wrote. Its absence means the
// file was written by a person, and is backed up rather than overwritten.
const generatedMarker = "generated by meerkat"

// Paths is where everything lives. Zero fields take the Debian defaults.
type Paths struct {
	// Staging is meerkat's own directory: the generated filter files, the
	// request and the result. Owned by the meerkat user, and the only directory
	// the unprivileged half writes.
	Staging string
	// ConfDir is where suricata-update reads its filter files from.
	ConfDir string
	// RulesFile is the built ruleset Suricata loads — what meerkat reads to
	// know what is actually running.
	RulesFile    string
	DataDir      string
	SuricataConf string
	Socket       string
	UpdateBin    string
}

// Defaults are Debian's layout, which is what edge1 runs.
func (p Paths) Defaults() Paths {
	if p.Staging == "" {
		p.Staging = "/var/lib/meerkat/suricata"
	}
	if p.ConfDir == "" {
		p.ConfDir = "/etc/suricata"
	}
	if p.RulesFile == "" {
		p.RulesFile = "/var/lib/suricata/rules/suricata.rules"
	}
	if p.DataDir == "" {
		p.DataDir = "/var/lib/suricata"
	}
	if p.SuricataConf == "" {
		p.SuricataConf = filepath.Join(p.ConfDir, "suricata.yaml")
	}
	if p.Socket == "" {
		p.Socket = "/var/run/suricata-command.socket"
	}
	return p
}

func (p Paths) StagedDisable() string { return filepath.Join(p.Staging, "disable.conf") }
func (p Paths) StagedEnable() string  { return filepath.Join(p.Staging, "enable.conf") }
func (p Paths) LiveDisable() string   { return filepath.Join(p.ConfDir, "disable.conf") }
func (p Paths) LiveEnable() string    { return filepath.Join(p.ConfDir, "enable.conf") }
func (p Paths) RequestFile() string   { return filepath.Join(p.Staging, "apply.request") }
func (p Paths) ResultFile() string    { return filepath.Join(p.Staging, "apply.result") }

// Request is what the console asks for, left in the staging directory for the
// privileged step to pick up.
type Request struct {
	RequestedAt time.Time `json:"requested_at"`
	Actor       string    `json:"actor"`
	Reason      string    `json:"reason"`
	// Force rebuilds even when the upstream ruleset has not changed. A policy
	// change needs it; a scheduled update does not, and leaving it off lets an
	// unchanged day be a no-op instead of a needless reload.
	Force bool `json:"force"`
}

// Result is what happened, written back for the console to record.
type Result struct {
	StartedAt  time.Time `json:"started_at"`
	FinishedAt time.Time `json:"finished_at"`
	Actor      string    `json:"actor"`
	Reason     string    `json:"reason"`
	OK         bool      `json:"ok"`
	// Step is where it got to, so a failure says which of the four things broke.
	Step  string `json:"step"`
	Error string `json:"error,omitempty"`

	Command  string        `json:"command,omitempty"`
	ExitCode int           `json:"exit_code"`
	Duration time.Duration `json:"duration"`
	Log      string        `json:"log,omitempty"`

	Reloaded     bool   `json:"reloaded"`
	ReloadDetail string `json:"reload_detail,omitempty"`

	Counts Counts `json:"counts"`
}

// The steps, in order. Named so a failure report can say where it stopped.
const (
	StepInstall = "installing the filter files"
	StepUpdate  = "running suricata-update"
	StepCount   = "reading the rebuilt ruleset"
	StepReload  = "asking suricata to reload"
	StepDone    = "done"
)

// Apply performs the privileged half: install the staged filter files, rebuild
// the ruleset, count what came out, and reload the sensor.
//
// It never returns an error — the outcome IS the result, including the failure,
// because the console needs to record and show a failed apply just as much as a
// successful one. A run that gets three steps in and fails on the fourth still
// reports the three.
func Apply(ctx context.Context, p Paths, req Request) Result {
	p = p.Defaults()
	res := Result{StartedAt: time.Now().UTC(), Actor: req.Actor, Reason: req.Reason, Step: StepInstall}

	finish := func(step string, err error) Result {
		res.Step, res.FinishedAt = step, time.Now().UTC()
		if err != nil {
			res.Error = err.Error()
			res.OK = false
			return res
		}
		res.OK = true
		return res
	}

	if err := installFilters(p); err != nil {
		return finish(StepInstall, err)
	}

	u := &Updater{
		Bin:          p.UpdateBin,
		SuricataConf: p.SuricataConf,
		DataDir:      p.DataDir,
		DisableConf:  p.LiveDisable(),
		EnableConf:   p.LiveEnable(),
	}
	out, err := u.Run(ctx, req.Force)
	res.Command, res.ExitCode, res.Duration, res.Log = out.Command, out.ExitCode, out.Duration, out.Log
	if err != nil {
		return finish(StepUpdate, err)
	}

	// Read back what was actually built. This is the step that keeps the whole
	// feature honest: suricata-update re-enables disabled rules that other
	// enabled rules depend on for flowbits, so "I disabled 299 rules" and "299
	// rules are disabled" are genuinely different claims, and meerkat reports
	// the second one.
	counts, err := ScanFile(p.RulesFile, func(Rule) error { return nil })
	if err != nil {
		return finish(StepCount, err)
	}
	res.Counts = counts

	// A stopped sensor is not a failed apply. The rules are on disk and will be
	// loaded when it starts; say so rather than reporting a broken run.
	ctl := NewControl(p.Socket, 0)
	if !ctl.Available() {
		res.ReloadDetail = "suricata is not running — the new ruleset will be loaded when it starts"
		return finish(StepDone, nil)
	}
	reply, err := ctl.Reload(ctx)
	if err != nil {
		res.ReloadDetail = err.Error()
		return finish(StepReload, fmt.Errorf("the ruleset was rebuilt but suricata would not reload it: %w", err))
	}
	if !reply.OK() {
		res.ReloadDetail = reply.Text()
		return finish(StepReload, fmt.Errorf("the ruleset was rebuilt but suricata refused it: %s", reply.Text()))
	}
	res.Reloaded = true
	res.ReloadDetail = strings.TrimSpace(reply.Text())
	if res.ReloadDetail == "" {
		res.ReloadDetail = "suricata reloaded the ruleset"
	}
	return finish(StepDone, nil)
}

// installFilters copies the staged filter files into the directory
// suricata-update reads, preserving anything a person put there first.
func installFilters(p Paths) error {
	for _, f := range []struct{ from, to string }{
		{p.StagedDisable(), p.LiveDisable()},
		{p.StagedEnable(), p.LiveEnable()},
	} {
		body, err := os.ReadFile(f.from)
		if errors.Is(err, os.ErrNotExist) {
			continue // nothing staged for this one
		}
		if err != nil {
			return fmt.Errorf("read %s: %w", f.from, err)
		}
		if err := backupIfHandWritten(f.to); err != nil {
			return err
		}
		if err := writeFileAtomic(f.to, body, 0o644); err != nil {
			return err
		}
	}
	return nil
}

// backupIfHandWritten preserves a filter file meerkat did not write.
//
// edge1's /etc/suricata/disable.conf already held a hand-added sid when meerkat
// arrived. Overwriting it would have silently switched that rule back on — a
// change nobody asked for, made by a tool claiming to be in charge of exactly
// that. The copy is kept once, next to the original, and meerkat's own adoption
// step reads it so the entry survives in the policy instead of being lost.
func backupIfHandWritten(path string) error {
	body, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if strings.Contains(string(body), generatedMarker) {
		return nil // ours; nothing to preserve
	}
	backup := path + ".pre-meerkat"
	if _, err := os.Stat(backup); err == nil {
		return nil // already preserved on an earlier run; never overwrite it
	}
	return writeFileAtomic(backup, body, 0o644)
}

// writeFileAtomic writes via a temp file in the same directory and renames, so
// a reader — suricata-update, or a person — never sees a half-written filter
// file, and an interrupted write leaves the old one intact.
func writeFileAtomic(path string, body []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".meerkat-*")
	if err != nil {
		return fmt.Errorf("create temp in %s: %w", dir, err)
	}
	name := tmp.Name()
	defer os.Remove(name) // no-op once the rename has succeeded

	if _, err := tmp.Write(body); err != nil {
		tmp.Close()
		return fmt.Errorf("write %s: %w", name, err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return fmt.Errorf("sync %s: %w", name, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close %s: %w", name, err)
	}
	if err := os.Chmod(name, mode); err != nil {
		return fmt.Errorf("chmod %s: %w", name, err)
	}
	if err := os.Rename(name, path); err != nil {
		return fmt.Errorf("rename onto %s: %w", path, err)
	}
	return nil
}

// ReadRequest loads a pending request, if there is one.
func ReadRequest(p Paths) (Request, bool, error) {
	body, err := os.ReadFile(p.Defaults().RequestFile())
	if errors.Is(err, os.ErrNotExist) {
		return Request{}, false, nil
	}
	if err != nil {
		return Request{}, false, err
	}
	var req Request
	if err := json.Unmarshal(body, &req); err != nil {
		return Request{}, false, fmt.Errorf("suricata: unreadable apply request: %w", err)
	}
	return req, true, nil
}

// WriteRequest asks for an apply. Written atomically because a systemd path
// unit watches for the file and would otherwise fire on an empty one.
func WriteRequest(p Paths, req Request) error {
	p = p.Defaults()
	if err := os.MkdirAll(p.Staging, 0o750); err != nil {
		return err
	}
	body, err := json.MarshalIndent(req, "", "  ")
	if err != nil {
		return err
	}
	return writeFileAtomic(p.RequestFile(), body, 0o640)
}

// ClearRequest removes a handled request. Doing this last is what makes the
// systemd path unit fire again for the next one.
func ClearRequest(p Paths) error {
	err := os.Remove(p.Defaults().RequestFile())
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	return err
}

// WriteResult records the outcome where the console can read it.
func WriteResult(p Paths, res Result) error {
	body, err := json.MarshalIndent(res, "", "  ")
	if err != nil {
		return err
	}
	// World-readable on purpose: root writes it and the meerkat user reads it.
	return writeFileAtomic(p.Defaults().ResultFile(), body, 0o644)
}

// ReadResult loads the last outcome, if there is one.
func ReadResult(p Paths) (Result, bool, error) {
	body, err := os.ReadFile(p.Defaults().ResultFile())
	if errors.Is(err, os.ErrNotExist) {
		return Result{}, false, nil
	}
	if err != nil {
		return Result{}, false, err
	}
	var res Result
	if err := json.Unmarshal(body, &res); err != nil {
		return Result{}, false, fmt.Errorf("suricata: unreadable apply result: %w", err)
	}
	return res, true, nil
}

// ClearResult removes a result the console has recorded.
func ClearResult(p Paths) error {
	err := os.Remove(p.Defaults().ResultFile())
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	return err
}
