package suricata

import (
	"bytes"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"time"
)

// The two scopes a policy entry can have. A sid names one rule; a category
// names every rule whose message starts with it, which is how "I do not care
// about ICMP" gets expressed once instead of 105 times.
const (
	ScopeSID      = "sid"
	ScopeCategory = "category"
)

// The states an operator can put a rule or a category into. Empty means "leave
// it as the ruleset ships it", which is not the same as enabling it — most of
// ET Open ships disabled, and meerkat must not silently turn 16,000 rules on.
const (
	StateDefault  = ""
	StateEnabled  = "enabled"
	StateDisabled = "disabled"
)

// Filter is one line meerkat will ask suricata-update to apply.
type Filter struct {
	Scope string
	Key   string
	// Note is the operator's reason, rendered as a comment above the line so
	// /etc/suricata/disable.conf explains itself to someone reading it over SSH
	// who has never heard of meerkat.
	Note string
}

// Matcher renders the filter in suricata-update's own syntax.
//
// A sid is written as the bare number. A category has no native representation
// — suricata-update's group: filter matches the source *filename*, and ET's
// filenames do not line up with message prefixes (ET CINS lives in
// emerging-ciarmy.rules) — so it is written as a regex against the message.
// Expanding a category to its member sids instead would be exact, but ET
// MALWARE alone is 26,000 rules and suricata-update matches every filter
// against every rule, so the file would take longer to build than to download.
func (f Filter) Matcher() string {
	switch f.Scope {
	case ScopeSID:
		return f.Key
	case ScopeCategory:
		return `re:msg:"` + regexp.QuoteMeta(f.Key) + ` `
	}
	return ""
}

// Filters is a complete policy, ready to be written out.
type Filters struct {
	Disable []Filter
	Enable  []Filter
}

// Render writes one filter file. suricata-update applies disable filters first
// and enable filters second, so a rule explicitly enabled beats a category-wide
// disable — which is what "mute all of ET CINS except this one" needs.
func Render(kind string, filters []Filter, generatedAt time.Time) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s.conf — generated by meerkat at %s. Do not edit by hand:\n",
		kind, generatedAt.UTC().Format(time.RFC3339))
	b.WriteString("# meerkat rewrites this file from its own rule policy every time it applies\n")
	b.WriteString("# a change, and anything added here will be lost. Change it in the meerkat\n")
	b.WriteString("# UI under Rules instead.\n")
	if len(filters) == 0 {
		b.WriteString("#\n# (nothing " + kind + "d)\n")
		return b.Bytes()
	}
	b.WriteString("\n")

	sorted := append([]Filter(nil), filters...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].Scope != sorted[j].Scope {
			return sorted[i].Scope < sorted[j].Scope
		}
		return sorted[i].Key < sorted[j].Key
	})
	for _, f := range sorted {
		m := f.Matcher()
		if m == "" {
			continue
		}
		if note := cleanNote(f.Note); note != "" {
			fmt.Fprintf(&b, "# %s\n", note)
		}
		b.WriteString(m)
		b.WriteString("\n")
	}
	return b.Bytes()
}

// cleanNote flattens an operator's reason to a single safe comment line. A
// newline in it would otherwise turn the rest of the reason into a filter line
// of its own, which is a config-injection bug however unlikely the typist.
func cleanNote(s string) string {
	s = strings.Map(func(r rune) rune {
		if r == '\n' || r == '\r' {
			return ' '
		}
		return r
	}, s)
	s = strings.TrimSpace(s)
	if len(s) > 160 {
		s = s[:160] + "…"
	}
	return s
}

// DisableConf and EnableConf render the two files suricata-update reads.
//
// There is deliberately no DropConf. suricata-update can rewrite a rule's
// action to "drop", and meerkat will not do it: Suricata here runs inline on
// NFQUEUE, dropping from it once cost 9.6% of transit traffic, and blocking is
// nftables' job. "Always block this" is implemented by meerkat pushing the
// source to nftably when the rule fires — not by handing the sensor a gun.
func (f Filters) DisableConf(at time.Time) []byte { return Render("disable", f.Disable, at) }
func (f Filters) EnableConf(at time.Time) []byte  { return Render("enable", f.Enable, at) }
